angular
    .module('ligneL')
    .constant('LIB_GARE', [

{code:'0',    latitude: '', longitude: '', name: ': Toutes directions'},
{code: 'AB',  latitude: '', longitude: '', name: 'Aulnay sous Bois'},
{code: 'ABL', latitude: '', longitude: '', name: 'Ablon'},
{code: 'ACW', latitude: '', longitude: '', name: 'Achères-Ville'},
{code: 'AEE', latitude: '', longitude: '', name: 'Asnières sur Seine'},
{code: 'AEH', latitude: '', longitude: '', name: 'Aubergenville Elisabethville'},
{code: 'AHM', latitude: '', longitude: '', name: 'Avenue Henri Martin'},
{code: 'ALC', latitude: '', longitude: '', name: 'Aubervilliers La Courneuve'},
{code: 'ANY', latitude: '', longitude: '', name: 'Andrésy'},
{code: 'APK', latitude: '', longitude: '', name: 'Avenue du Président Kennedy'},
{code: 'ARK', latitude: '', longitude: '', name: 'Arcueil Cachan'},
{code: 'ARP', latitude: '', longitude: '', name: 'Arpajon'},
{code: 'ARW', latitude: '', longitude: '', name: 'Argenteuil'},
{code: 'ATH', latitude: '', longitude: '', name: 'Athis Mons'},
{code: 'ATW', latitude: '', longitude: '', name: 'Antony'},
{code: 'AUU', latitude: '', longitude: '', name: 'Auber'},
{code: 'AUW', latitude: '', longitude: '', name: 'Auvers-sur-Oise'},
{code: 'AVF', latitude: '', longitude: '', name: 'Avenue Foch'},
{code: 'BAM', latitude: '', longitude: '', name: 'Blanc Mesnil'},
{code: 'BBN', latitude: '', longitude: '', name: 'La Borne Blanche'},
{code: 'BCO', latitude: '', longitude: '', name: 'Bois Colombes',²
{code: 'BDE', latitude: '', longitude: '', name: 'Sevran Beaudottes'},
{code: 'BDY', latitude: '', longitude: '', name: 'Bondy' },
{code: 'BEC', latitude: '', longitude: '', name: 'Bécon les Bruyères'},
{code: 'BFM', latitude: '', longitude: '', name: 'Bibliothèque François Mitterrand'},
{code: 'BFX', latitude: '', longitude: '', name: 'Le Bras de Fer'},
{code: 'BGK', latitude: '', longitude: '', name: 'Bagneux'},
{code: 'BGV', latitude: '', longitude: '', name: 'Bougival'},
{code: 'BIH', latitude: '', longitude: '', name: 'Breuillet Bruyères le Chatel'},
{code: 'BIS', latitude: '', longitude: '', name: 'Bièvres'},
{code: 'BJN', latitude: '', longitude: '', name: 'Boutigny'},
{code: 'BJR', latitude: '', longitude: '', name: 'Bois Le Roi'},
{code: 'BKR', latitude: '', longitude: '', name: 'Boissise-le-Roi'},
{code: 'BLA', latitude: '', longitude: '', name: "Boissy-l'Aillerie"},
{code: 'BLU', latitude: '', longitude: '', name: 'Bellevue'},
{code: 'BNY', latitude: '', longitude: '', name: 'Brunoy'},
{code: 'BOF', latitude: '', longitude: '', name: 'Bouffemont Moisselles'},
{code: 'BOM', latitude: '', longitude: '', name: 'Bourron Marlotte Grez'},
{code: 'BQA', latitude: '', longitude: '', name: 'Bry sur Marne'},
{code: 'BQC', latitude: '', longitude: '', name: 'Les Baconnets'},
{code: 'BQQ', latitude: '', longitude: '', name: 'Bourg la Reine'},
{code: 'BQV', latitude: '', longitude: '', name: 'Buno-Gironville'},
{code: 'BRK', latitude: '', longitude: '', name: 'Bruyères-sur-Oise'},
{code: 'BRN', latitude: '', longitude: '', name: 'Boran-sur-Oise'},
{code: 'BRW', latitude: '', longitude: '', name: 'Breuillet Village'},
{code: 'BSO', latitude: '', longitude: '', name: 'Bouray'},
{code: 'BSR', latitude: '', longitude: '', name: 'Bessancourt'},
{code: 'BSW', latitude: '', longitude: '', name: 'Belloy - Saint-Martin'},
{code: 'BUR', latitude: '', longitude: '', name: 'Ballancourt'},
{code: 'BVI', latitude: '', longitude: '', name: 'Boulevard Victor - Pont du Garigliano'},
{code: 'BVJ', latitude: '', longitude: '', name: 'Bures sur Yvette'},
{code: 'BWI', latitude: '', longitude: '', name: 'Boigneville'},
{code: 'BWR', latitude: '', longitude: '', name: 'Boulainvilliers'},
{code: 'BXG', latitude: '', longitude: '', name: 'Bussy Saint-Georges'},
{code: 'BXI', latitude: '', longitude: '', name: 'Boussy Saint-Antoine'},
{code: 'BXN', latitude: '', longitude: '', name: 'Bagneaux sur Loing'},
{code: 'BXP', latitude: '', longitude: '', name: 'Les Boullereaux Champigny'},
{code: 'BXR', latitude: '', longitude: '', name: 'Boissy Saint-Léger'},
{code: 'BY' , latitude: '', longitude: '', name: 'Brétigny'},
{code: 'BYS', latitude: '', longitude: '', name: 'Beynes'},
{code: 'CAZ', latitude: '', longitude: '', name: 'Chilly Mazarin'},
{code: 'CBK', latitude: '', longitude: '', name: 'Colombes'},
{code: 'CBV', latitude: '', longitude: '', name: 'Combs la Ville Quincy'},
{code: 'CEG', latitude: '', longitude: '', name: "Champ de Courses d'Enghien"},
{code: 'CEJ', latitude: '', longitude: '', name: 'Cernay'},
{code: 'CES', latitude: '', longitude: '', name: 'Cesson'},
{code: 'CEV', latitude: '', longitude: '', name: 'Chaumont-en-Vexin'},
{code: 'CEX', latitude: '', longitude: '', name: 'Le Coudray-Monceaux'},
{code: 'CFD', latitude: '', longitude: '', name: "Conflans-Fin-d'Oise"},
{code: 'CGG', latitude: '', longitude: '', name: 'Chenay Gagny' },
{code: 'CGJ', latitude: '', longitude: '', name: 'Champigny'},
{code: 'CGP', latitude: '', longitude: '', name: 'Charles de Gaulle-Étoile'},
{code: 'CGW', latitude: '', longitude: '', name: 'Coignières'},
{code: 'CH' , latitude: '', longitude: '', name: 'Chartres'},
{code: 'CHK', latitude: '', longitude: '', name: 'Chamarande'},
{code: 'CHQ', latitude: '', longitude: '', name: "Chemin d'Antony"},
{code: 'CHR', latitude: '', longitude: '', name: 'Chars'},
{code: 'CHV', latitude: '', longitude: '', name: 'Chaville Vélizy'},
{code: 'CJN', latitude: '', longitude: '', name: 'Changis Saint-Jean'},
{code: 'CJR', latitude: '', longitude: '', name: 'Chartrettes'},
{code: 'CJV', latitude: '', longitude: '', name: 'Cergy le Haut'},
{code: 'CL' , latitude: '', longitude: '', name: 'Creil'},
{code: 'CLC', latitude: '', longitude: '', name: 'Crécy-la-Chapelle'},
{code: 'CLL', latitude: '', longitude: '', name: 'Clichy Levallois'},
{code: 'CLR', latitude: '', longitude: '', name: 'Choisy le Roi'},
{code: 'CLX', latitude: '', longitude: '', name: 'Châtelet les Halles'},
{code: 'CLY', latitude: '', longitude: '', name: 'Chantilly Gouvieux'},
{code: 'CMA', latitude: '', longitude: '', name: 'Clamart'},
{code: 'CME', latitude: '', longitude: '', name: 'Champagne sur Seine'},
{code: 'CO' , latitude: '', longitude: '', name: 'Coulommiers'},
{code: 'COE', latitude: '', longitude: '', name: 'Corbeil Essonnes'},
{code: 'COJ', latitude: '', longitude: '', name: 'Compans'},
{code: 'CPA', latitude: '', longitude: '', name: 'Cormeilles en Parisis'},
{code: 'CPK', latitude: '', longitude: '', name: 'Champbenoist - Poigny'},
{code: 'CPM', latitude: '', longitude: '', name: 'Champ de Mars Tour Eiffel'},
{code: 'CPO', latitude: '', longitude: '', name: 'Champagne sur Oise'},
{code: 'CPW', latitude: '', longitude: '', name: 'Chaponval'},
{code: 'CQQ', latitude: '', longitude: '', name: 'Crouy-sur-Ourcq'},
{code: 'CSG', latitude: '', longitude: '', name: 'Chelles Gournay'},
{code: 'CSH', latitude: '', longitude: '', name: 'Conflans Sainte Honorine'},
{code: 'CTH', latitude: '', longitude: '', name: 'Château Thierry'},
{code: 'CUF', latitude: '', longitude: '', name: 'Cité Universitaire'},
{code: 'CVF', latitude: '', longitude: '', name: 'Chanteloup les Vignes'},
{code: 'CVI', latitude: '', longitude: '', name: 'Chaville Rive Gauche'},
{code: 'CVW', latitude: '', longitude: '', name: 'Courcelles sur Yvette'},
{code: 'CWJ', latitude: '', longitude: '', name: 'Chaville Rive Droite'},
{code: 'CXA', latitude: '', longitude: '', name: 'Châtelet les Halles RER A'},
{code: 'CYC', latitude: '', longitude: '', name: 'Cergy Saint-Christophe'},
{code: 'CYP', latitude: '', longitude: '', name: 'Cergy Préfecture'},
{code: 'CYQ', latitude: '', longitude: '', name: 'Couilly Saint-Germain Quincy'},
{code: 'CYV', latitude: '', longitude: '', name: 'Crépy-en-Valois'},
{code: 'CYZ', latitude: '', longitude: '', name: 'Chézy sur Marne'},
{code: 'D'  , latitude: '', longitude: '', name: 'Dourdan'},
{code: 'DA' , latitude: '', longitude: '', name: 'Dourdan la Forêt'},
{code: 'DAM', latitude: '', longitude: '', name: 'Dammartin Juilly-Saint-Mard'},
{code: 'DDI', latitude: '', longitude: '', name: 'Dordives'},
{code: 'DEU', latitude: '', longitude: '', name: 'Deuil Montmagny'},
{code: 'DFR', latitude: '', longitude: '', name: 'Denfert Rochereau'},
{code: 'DMO', latitude: '', longitude: '', name: 'Domont'},
{code: 'DRN', latitude: '', longitude: '', name: 'Drancy'},
{code: 'DX' , latitude: '', longitude: '', name: 'Dreux'},
{code: 'ECZ', latitude: '', longitude: '', name: 'Écouen Ézanville'},
{code: 'ELW', latitude: '', longitude: '', name: "L'Étang-la-Ville"},
{code: 'ELY', latitude: '', longitude: '', name: 'Égly'},
{code: 'EM' , latitude: '', longitude: '', name: 'Emerainville Pontault Combault'},
{code: 'EN' , latitude: '', longitude: '', name: 'Enghien les Bains'},
{code: 'EPL', latitude: '', longitude: '', name: 'Épluches'},
{code: 'EPN', latitude: '', longitude: '', name: 'Épernon'},
{code: 'EPO', latitude: '', longitude: '', name: 'Épone Mézières'},
{code: 'EPV', latitude: '', longitude: '', name: 'Épinay Villetaneuse'},
{code: 'ERA', latitude: '', longitude: '', name: 'Éragny Neuville'},
{code: 'ERM', latitude: '', longitude: '', name: 'Ermont Halte'},
{code: 'ERT', latitude: '', longitude: '', name: 'Ermont Eaubonne'},
{code: 'ESO', latitude: '', longitude: '', name: 'Essonnes-Robinson'},
{code: 'ETP', latitude: '', longitude: '', name: 'Étampes'},
{code: 'ETY', latitude: '', longitude: '', name: 'Étrechy'},
{code: 'EVC', latitude: '', longitude: '', name: 'Évry Courcouronnes'},
{code: 'EVR', latitude: '', longitude: '', name: 'Évry'},
{code: 'EY' , latitude: '', longitude: '', name: 'Esbly'},
{code: 'EYO', latitude: '', longitude: '', name: 'Épinay sur Orge'},
{code: 'EYS', latitude: '', longitude: '', name: 'Épinay sur Seine'},
{code: 'FAF', latitude: '', longitude: '', name: 'Fontenay le Fleury'},
{code: 'FFY', latitude: '', longitude: '', name: 'Ferrières Fontenay'},
{code: 'FMN', latitude: '', longitude: '', name: 'Fontaine Michalon'},
{code: 'FMP', latitude: '', longitude: '', name: 'Faremoutiers Pommeuse'},
{code: 'FMY', latitude: '', longitude: '', name: 'La Frette Montigny'},
{code: 'FNR', latitude: '', longitude: '', name: 'Fontenay aux Roses'},
{code: 'FON', latitude: '', longitude: '', name: 'Fontainebleau Avon'},
{code: 'FPB', latitude: '', longitude: '', name: 'Franconville Le Plessis Bouchard'},
{code: 'FPN', latitude: '', longitude: '', name: 'Frépillon'},
{code: 'FPO', latitude: '', longitude: '', name: 'Fontaine le Port'},
{code: 'FSB', latitude: '', longitude: '', name: 'Fontenay-sous-Bois'},
{code: 'GAJ', latitude: '', longitude: '', name: 'Garges Sarcelles'},
{code: 'GAQ', latitude: '', longitude: '', name: 'Garancières la Queue'},
{code: 'GAW', latitude: '', longitude: '', name: 'La Défense Grande Arche'},
{code: 'GBG', latitude: '', longitude: '', name: 'Grand Bourg'},
{code: 'GBI', latitude: '', longitude: '', name: 'Gravigny Balizy'},
{code: 'GCM', latitude: '', longitude: '', name: 'Guérard la Celle sur Morin'},
{code: 'GCR', latitude: '', longitude: '', name: 'Achères Grand Cormier'},
{code: 'GDS', latitude: '', longitude: '', name: 'Paris Nord'},
{code: 'PNB', latitude: '', longitude: '', name: 'Paris Nord'},
{code: 'GEN', latitude: '', longitude: '', name: 'Gennevilliers'},
{code: 'GGG', latitude: '', longitude: '', name: 'Grigny Centre'},
{code: 'GGV', latitude: '', longitude: '', name: 'Gargenville'},
{code: 'GIF', latitude: '', longitude: '', name: 'Gif sur Yvette'},
{code: 'GIS', latitude: '', longitude: '', name: 'Gisors'},
{code: 'GMC', latitude: '', longitude: '', name: 'Garches Marnes-la-Coquette'},
{code: 'GN' , latitude: '', longitude: '', name: 'Gagny' },
{code: 'GNX', latitude: '', longitude: '', name: 'Gros Noyer Saint-Prix'},
{code: 'GOU', latitude: '', longitude: '', name: 'Goussainville'},
{code: 'GPA', latitude: '', longitude: '', name: 'La Grande Paroisse'},
{code: 'GRL', latitude: '', longitude: '', name: 'Groslay'},
{code: 'GTL', latitude: '', longitude: '', name: 'Gentilly'},
{code: 'GUW', latitude: '', longitude: '', name: 'Le Guichet'},
{code: 'GYN', latitude: '', longitude: '', name: 'Gare de Lyon'},
{code: 'GZ' , latitude: '', longitude: '', name: 'Gretz Armainvilliers' },
{code: 'GZA', latitude: '', longitude: '', name: 'Gazeran'},
{code: 'HAQ', latitude: '', longitude: '', name: 'La Hacquinière'},
{code: 'HAR', latitude: '', longitude: '', name: 'Houilles Carrières sur Seine'},
{code: 'HER', latitude: '', longitude: '', name: 'Héricy'},
{code: 'HOA', latitude: '', longitude: '', name: 'Houdan'},
{code: 'HRY', latitude: '', longitude: '', name: 'Herblay'},
{code: 'HSL', latitude: '', longitude: '', name: 'Haussman Saint-Lazare' },
{code: 'IAC', latitude: '', longitude: '', name: 'Isles-Armentières-Congis'},
{code: 'IAP', latitude: '', longitude: '', name: "L'Isle Adam Parmain"},
{code: 'IBM', latitude: '', longitude: '', name: 'Le Plessis-Chenet'},
{code: 'IGY', latitude: '', longitude: '', name: 'Igny'},
{code: 'INV', latitude: '', longitude: '', name: 'Invalides'},
{code: 'IPO', latitude: '', longitude: '', name: 'Issou Porcheville'},
{code: 'ISP', latitude: '', longitude: '', name: 'Issy Val de Seine'},
{code: 'ISY', latitude: '', longitude: '', name: 'Issy'},
{code: 'IV' , latitude: '', longitude: '', name: 'Ivry sur Seine'},
{code: 'JAS', latitude: '', longitude: '', name: 'Jouy en Josas'},
{code: 'JOY', latitude: '', longitude: '', name: 'Jouy'},
{code: 'JUZ', latitude: '', longitude: '', name: 'Juziers'},
{code: 'JVL', latitude: '', longitude: '', name: 'Javel'},
{code: 'JVR', latitude: '', longitude: '', name: 'Joinville-le-Pont'},
{code: 'JY' , latitude: '', longitude: '', name: 'Juvisy'},
{code: 'KOU', latitude: '', longitude: '', name: 'Courbevoie'},
{code: 'KRW', latitude: '', longitude: '', name: 'Montgeron Crosne'},
{code: 'KVE', latitude: '', longitude: '', name: 'Les Clairières de Verneuil'},
{code: 'LAD', latitude: '', longitude: '', name: 'Les Ardoines'},
{code: 'LBJ', latitude: '', longitude: '', name: 'La Barre Ormesson'},
{code: 'LBT', latitude: '', longitude: '', name: 'Le Bourget'},
{code: 'LCB', latitude: '', longitude: '', name: 'La Celle-Saint-Cloud'},
{code: 'LDU', latitude: '', longitude: '', name: 'La Défense'},
{code: 'LEG', latitude: '', longitude: '', name: 'Les Grésillons'},
{code: 'LFA', latitude: '', longitude: '', name: 'La Ferté Alais'},
{code: 'LFC', latitude: '', longitude: '', name: 'Louveciennes'},
{code: 'LFJ', latitude: '', longitude: '', name: 'La Ferté sous Jouarre'},
{code: 'LFM', latitude: '', longitude: '', name: 'La Ferté Milon'},
{code: 'LGK', latitude: '', longitude: '', name: 'La Garenne Colombes'},
{code: 'LGY', latitude: '', longitude: '', name: 'Lagny Thorigny'},
{code: 'LIE', latitude: '', longitude: '', name: "Saint-Ouen l'Aumône Liesse"},
{code: 'LIM', latitude: '', longitude: '', name: 'Limay'},
{code: 'LIU', latitude: '', longitude: '', name: 'Lieusaint Moissy'},
{code: 'LJA', latitude: '', longitude: '', name: 'Laplace'},
{code: 'LJU', latitude: '', longitude: '', name: 'Longjumeau'},
{code: 'LMU', latitude: '', longitude: '', name: 'Les Mureaux'},
{code: 'LNX', latitude: '', longitude: '', name: 'Les Noues'},
{code: 'LON', latitude: '', longitude: '', name: 'Longueville', 
{code: 'LOV', latitude: '', longitude: '', name: 'Louvres'},
{code: 'LPE', latitude: '', longitude: '', name: 'Le Perray'},
{code: 'LPN', latitude: '', longitude: '', name: 'La Plaine Stade de France'},
{code: 'LQK', latitude: '', longitude: '', name: 'Liancourt-Saint-Pierre'},
{code: 'LQN', latitude: '', longitude: '', name: 'Lognes'},
{code: 'LSD', latitude: '', longitude: '', name: 'Le Stade'},
{code: 'LSI', latitude: '', longitude: '', name: 'Les Essarts le Roi'},
{code: 'LSW', latitude: '', longitude: '', name: 'Les Saules'},
{code: 'LUZ', latitude: '', longitude: '', name: 'Luzarches'},
{code: 'LVZ', latitude: '', longitude: '', name: 'La Varenne Chennevières'},
{code: 'LWA', latitude: '', longitude: '', name: 'Les Vallées'},
{code: 'LXJ', latitude: '', longitude: '', name: 'Luxembourg'},
{code: 'LYO', latitude: '', longitude: '', name: 'Lardy'},
{code: 'LYQ', latitude: '', longitude: '', name: 'Livry sur Seine'},
{code: 'LYV', latitude: '', longitude: '', name: 'Les Yvris Noisy Le Grand' },
{code: 'LZO', latitude: '', longitude: '', name: 'Lizy-sur-Ourcq'},
{code: 'LZV', latitude: '', longitude: '', name: 'Lozère'},
{code: 'MAE', latitude: '', longitude: '', name: 'Maule'},
{code: 'MGT', latitude: '', longitude: '', name: 'Magenta'},
{code: 'MAL', latitude: '', longitude: '', name: 'Malesherbes'},
{code: 'MAQ', latitude: '', longitude: '', name: 'Mareuil-sur-Ourcq'},
{code: 'MBP', latitude: '', longitude: '', name: 'Montigny Beauchamp'},
{code: 'MBR', latitude: '', longitude: '', name: 'Marchezais Broué'},
{code: 'MDN', latitude: '', longitude: '', name: 'Meudon'},
{code: 'MDS', latitude: '', longitude: '', name: "Musée d'Orsay"},
{code: 'MEA', latitude: '', longitude: '', name: 'Meaux'},
{code: 'MEL', latitude: '', longitude: '', name: 'Melun'},
{code: 'MFA', latitude: '', longitude: '', name: 'Maisons Alfort Alfortville'},
{code: 'MFL', latitude: '', longitude: '', name: 'Montreuil'},
{code: 'MFY', latitude: '', longitude: '', name: 'Meudon Val Fleury'},
{code: 'MHD', latitude: '', longitude: '', name: 'Meulan Hardricourt'},
{code: 'MJM', latitude: '', longitude: '', name: 'Mareil sur Mauldre'},
{code: 'MJW', latitude: '', longitude: '', name: 'Moulin-Galant'},
{code: 'MKN', latitude: '', longitude: '', name: 'Montigny sur Loing'},
{code: 'MKU', latitude: '', longitude: '', name: 'Montgeroult - Courcelles'},
{code: 'MLB', latitude: '', longitude: '', name: 'Marles en Brie'},
{code: 'MLF', latitude: '', longitude: '', name: 'Maisons Laffitte'},
{code: 'MLM', latitude: '', longitude: '', name: "Montfort l'Amaury Méré"},
{code: 'MLR', latitude: '', longitude: '', name: 'Marly-le-Roi'},
{code: 'MLV', latitude: '', longitude: '', name: 'Meriel'},
{code: 'MNY', latitude: '', longitude: '', name: 'Mennecy'},
{code: 'MOF', latitude: '', longitude: '', name: 'Mortcerf'},
{code: 'MOR', latitude: '', longitude: '', name: 'Morêt Veneux les Sablons'},
{code: 'MP' , latitude: '', longitude: '', name: 'Massy Palaiseau RER B'},
{code: 'MPU', latitude: '', longitude: '', name: 'Massy Palaiseau RER C'},
{code: 'MRK', latitude: '', longitude: '', name: 'Maurecourt'},
{code: 'MRT', latitude: '', longitude: '', name: 'Mormant'},
{code: 'MS' , latitude: '', longitude: '', name: 'Montargis'},
{code: 'MSN', latitude: '', longitude: '', name: 'Maisse'},
{code: 'MSO', latitude: '', longitude: '', name: 'Montsoult Maffliers'},
{code: 'MSX', latitude: '', longitude: '', name: 'Marolles en Hurepoix'},
{code: 'MTE', latitude: '', longitude: '', name: 'Mantes la Jolie'},
{code: 'MTN', latitude: '', longitude: '', name: 'Maintenon'},
{code: 'MTQ', latitude: '', longitude: '', name: 'Mantes Station'},
{code: 'MTU', latitude: '', longitude: '', name: 'Montereau'},
{code: 'MVC', latitude: '', longitude: '', name: 'Marne la Vallée Chessy'},
{code: 'MVH', latitude: '', longitude: '', name: 'Suresnes Mont Valérien'},
{code: 'MVP', latitude: '', longitude: '', name: 'Massy Verrières RER B'},
{code: 'MVW', latitude: '', longitude: '', name: 'Massy Verrières RER C'},
{code: 'MWO', latitude: '', longitude: '', name: 'Méry sur Oise', 
{code: 'MXK', latitude: '', longitude: '', name: 'Mouroux'},
{code: 'MY' , latitude: '', longitude: '', name: 'Mitry Claye'},
{code: 'MYD', latitude: '', longitude: '', name: 'Montry Condé'},
{code: 'NAA', latitude: '', longitude: '', name: "Nogent l'Artaud Charly"},
{code: 'NAF', latitude: '', longitude: '', name: 'Nanterre Préfecture'},
{code: 'NAN', latitude: '', longitude: '', name: 'Nangis'},
{code: 'NAU', latitude: '', longitude: '', name: 'Nanteuil Saacy'},
{code: 'NC1', latitude: '', longitude: '', name: 'Saint-Germain-en-Laye'},
{code: 'NC2', latitude: '', longitude: '', name: 'Le Vésinet Le Pecq'},
{code: 'NC3', latitude: '', longitude: '', name: 'Nanterre Ville'},
{code: 'NC4', latitude: '', longitude: '', name: 'Le Vésinet-Centre'},
{code: 'NC5', latitude: '', longitude: '', name: 'Chatou-Croissy'},
{code: 'NC6', latitude: '', longitude: '', name: 'Rueil-Malmaison'},
{code: 'NG' , latitude: '', longitude: '', name: 'La Norville Saint-Germain lès Arpajon'},
{code: 'NGM', latitude: '', longitude: '', name: 'Nogent-sur-Marne'},
{code: 'NH' , latitude: '', longitude: '', name: 'Nanteuil-le-Haudoin'},
{code: 'NLP', latitude: '', longitude: '', name: 'Nogent Le Perreux' },
{code: 'NO' , latitude: '', longitude: '', name: 'Nointel - Mours'},
{code: 'NPT', latitude: '', longitude: '', name: 'Neuilly Porte Maillot'},
{code: 'NSL', latitude: '', longitude: '', name: 'Noisiel'},
{code: 'NSP', latitude: '', longitude: '', name: 'Nemours Saint-Pierre'},
{code: 'NSY', latitude: '', longitude: '', name: 'Noisy Le Sec' },
{code: 'NTN', latitude: '', longitude: '', name: 'Nation'},
{code: 'NUE', latitude: '', longitude: '', name: 'Neuville Université'},
{code: 'NUN', latitude: '', longitude: '', name: 'Nanterre Université'},
{code: 'NYC', latitude: '', longitude: '', name: 'Noisy Champs'},
{code: 'NYG', latitude: '', longitude: '', name: "Noisy le Grand Mont d'Est"},
{code: 'NYP', latitude: '', longitude: '', name: 'Neuilly Plaisance'},
{code: 'NZL', latitude: '', longitude: '', name: 'Nezel Aulnay'},
{code: 'OBP', latitude: '', longitude: '', name: "Orangis Bois de l'Épine"},
{code: 'OGB', latitude: '', longitude: '', name: 'Orgerus Behoust'},
{code: 'ORM', latitude: '', longitude: '', name: 'Ormoy-Villers'},
{code: 'ORS', latitude: '', longitude: '', name: 'Orsay Ville'},
{code: 'ORY', latitude: '', longitude: '', name: 'Orry la Ville Coye'},
{code: 'OSN', latitude: '', longitude: '', name: 'Osny'},
{code: 'OY' , latitude: '', longitude: '', name: 'Orly Ville'},
{code: 'OZF', latitude: '', longitude: '', name: 'Ozoir la Ferrière' },
{code: 'PLY', latitude: '', longitude: '', name: 'Paris Gare de Lyon', 
{code: 'PAA', latitude: '', longitude: '', name: 'Paris Gare de Lyon'},
{code: 'PAN', latitude: '', longitude: '', name: 'Pantin' },
{code: 'PAW', latitude: '', longitude: '', name: 'Palaiseau Villebon'},
{code: 'PAX', latitude: '', longitude: '', name: 'Palaiseau'},
{code: 'PCX', latitude: '', longitude: '', name: 'Parc de Sceaux'},
{code: 'PDM', latitude: '', longitude: '', name: "Pont de l'Alma"},
{code: 'PE' , latitude: '', longitude: '', name: 'Paris Est'},
{code: 'PEB', latitude: '', longitude: '', name: 'Persan Beaumont'},
{code: 'PEX', latitude: '', longitude: '', name: 'Parc des Expositions'},
{code: 'PG' , latitude: '', longitude: '', name: 'Plaisir Grignon'},
{code: 'PIE', latitude: '', longitude: '', name: 'Plaisir les Clayes'},
{code: 'PJ' , latitude: '', longitude: '', name: 'Petit Jouy les Loges'},
{code: 'PKY', latitude: '', longitude: '', name: 'Porte de Clichy'},
{code: 'PLB', latitude: '', longitude: '', name: 'Plessis-Belleville'},
{code: 'PMP', latitude: '', longitude: '', name: 'Paris Montparnasse'},
{code: 'POA', latitude: '', longitude: '', name: 'Porchefontaine'},
{code: 'POP', latitude: '', longitude: '', name: 'Ponthierry-Pringy'},
{code: 'PPD', latitude: '', longitude: '', name: 'Créteil Pompadour', 
{code: 'PPT', latitude: '', longitude: '', name: 'Pont-Petit'},
{code: 'PRF', latitude: '', longitude: '', name: 'Pierrefitte Stains'},
{code: 'PRO', latitude: '', longitude: '', name: 'Provins'},
{code: 'PRQ', latitude: '', longitude: '', name: 'Presles - Courcelles'},
{code: 'PRR', latitude: '', longitude: '', name: 'Pereire Levallois'},
{code: 'PRU', latitude: '', longitude: '', name: "Pont de Rungis Aéroport d'Orly"},
{code: 'PRY', latitude: '', longitude: '', name: 'Pierrelaye'},
{code: 'PSE', latitude: '', longitude: '', name: 'Pontoise'},
{code: 'PSL', latitude: '', longitude: '', name: 'Paris Saint-Lazare'},
{code: 'PSY', latitude: '', longitude: '', name: 'Poissy'},
{code: 'PTC', latitude: '', longitude: '', name: 'Pont Cardinet'},
{code: 'PTX', latitude: '', longitude: '', name: 'Puteaux'},
{code: 'PV' , latitude: '', longitude: '', name: 'Petit Vaux'},
{code: 'PWR', latitude: '', longitude: '', name: 'Port Royal'},
{code: 'PXO', latitude: '', longitude: '', name: 'Le Parc de Saint-Maur'},
{code: 'PYO', latitude: '', longitude: '', name: 'Précy-sur-Oise'},
{code: 'PZB', latitude: '', longitude: '', name: 'Paris Austerlitz'},
{code: 'RBI', latitude: '', longitude: '', name: 'Rosny Bois Perrier' },
{code: 'RBT', latitude: '', longitude: '', name: 'Rambouillet'},
{code: 'RF' , latitude: '', longitude: '', name: 'Rungis la Fraternelle'},
{code: 'RIS', latitude: '', longitude: '', name: 'Ris Orangis'},
{code: 'RNS', latitude: '', longitude: '', name: 'Robinson'},
{code: 'ROB', latitude: '', longitude: '', name: 'Roissy en Brie' },
{code: 'RSB', latitude: '', longitude: '', name: 'Rosny sous Bois' },
{code: 'RSY', latitude: '', longitude: '', name: 'Aéroport Charles de Gaulle 1'},
{code: 'RVM', latitude: '', longitude: '', name: 'Le Raincy Villemomble' },
{code: 'RYR', latitude: '', longitude: '', name: 'Aéroport Charles de Gaulle 2 TGV'},
{code: 'SAO', latitude: '', longitude: '', name: 'Savigny sur Orge'},
{code: 'SCD', latitude: '', longitude: '', name: 'Saint-Cloud'},
{code: 'SCR', latitude: '', longitude: '', name: 'Saint-Cyr'},
{code: 'SCW', latitude: '', longitude: '', name: 'Saint-Chéron'},
{code: 'SDE', latitude: '', longitude: '', name: 'Saint-Denis'},
{code: 'SEV', latitude: '', longitude: '', name: 'Sevran Livry'},
{code: 'SF' , latitude: '', longitude: '', name: 'Saint-Mammes'},
{code: 'SFD', latitude: '', longitude: '', name: 'Stade de France Saint-Denis'},
{code: 'SGT', latitude: '', longitude: '', name: 'Saint-Gratien'},
{code: 'SHL', latitude: '', longitude: '', name: 'Saint-Michel Notre Dame RER C', 
{code: 'SHO', latitude: '', longitude: '', name: 'Saint-Michel sur Orge'},
{code: 'SKX', latitude: '', longitude: '', name: 'Sceaux'},
{code: 'SLF', latitude: '', longitude: '', name: 'Saint-Leu la Forêt'},
{code: 'SLL', latitude: '', longitude: '', name: 'Sarcelles Saint-Brice'},
{code: 'SLT', latitude: '', longitude: '', name: "Saint-Leu d'Esserent"},
{code: 'SME', latitude: '', longitude: '', name: "Saint-Martin d'Étampes"},
{code: 'SNB', latitude: '', longitude: '', name: 'Saint-Nom-la-Bretèche - Forêt de Marly'},
{code: 'SNM', latitude: '', longitude: '', name: 'Saint-Rémy lès Chevreuse'},
{code: 'SNN', latitude: '', longitude: '', name: 'Sannois'},
{code: 'SOA', latitude: '', longitude: '', name: "Saint-Ouen l'Aumône"},
{code: 'SOS', latitude: '', longitude: '', name: 'Saint-Ouen'},
{code: 'SPI', latitude: '', longitude: '', name: 'Saint-Piat'},
{code: 'SPP', latitude: '', longitude: '', name: 'Souppes Château Landon'},
{code: 'SQY', latitude: '', longitude: '', name: 'Saint-Quentin en Yvelines'},
{code: 'SUR', latitude: '', longitude: '', name: 'Survilliers Fosses'},
{code: 'SVL', latitude: '', longitude: '', name: 'Sartrouville'},
{code: 'SVR', latitude: '', longitude: '', name: 'Sèvres Rive Gauche'},
{code: 'SWY', latitude: '', longitude: '', name: 'Seugy'},
{code: 'SXE', latitude: '', longitude: '', name: 'Sermaise'},
{code: 'SXG', latitude: '', longitude: '', name: 'Sainte Geneviève des Bois'},
{code: 'TAE', latitude: '', longitude: '', name: 'Tacoignières Richebourg'},
{code: 'TLP', latitude: '', longitude: '', name: 'Trilport'},
{code: 'TMR', latitude: '', longitude: '', name: 'Thomery'},
{code: 'TNT', latitude: '', longitude: '', name: 'Thieux - Nantouillet'},
{code: 'TOC', latitude: '', longitude: '', name: 'Torcy'},
{code: 'TOU', latitude: '', longitude: '', name: 'Tournan'},
{code: 'TPA', latitude: '', longitude: '', name: 'Thun le Paradis'},
{code: 'TRH', latitude: '', longitude: '', name: 'Trie-Château'},
{code: 'TSS', latitude: '', longitude: '', name: 'Triel sur Seine'},
{code: 'TVO', latitude: '', longitude: '', name: 'Trappes'},
{code: 'TVY', latitude: '', longitude: '', name: 'Taverny'},
{code: 'US' , latitude: '', longitude: '', name: 'Us'},
{code: 'VAI', latitude: '', longitude: '', name: 'Vaires Torcy'},
{code: 'VBB', latitude: '', longitude: '', name: 'Villiers-Montbarbin'},
{code: 'VBO', latitude: '', longitude: '', name: 'Vauboyen'},
{code: 'VBV', latitude: '', longitude: '', name: 'Villabé'},
{code: 'VC' , latitude: '', longitude: '', name: 'Versailles Chantiers'},
{code: 'VCN', latitude: '', longitude: '', name: 'Vaucresson'},
{code: 'VCX', latitude: '', longitude: '', name: 'Vaucelles'},
{code: 'VD' , latitude: '', longitude: '', name: 'Le Vert de Maisons'},
{code: 'VDA', latitude: '', longitude: '', name: "Val d'Argenteuil"},
{code: 'VDE', latitude: '', longitude: '', name: "Val d'Europe"},
{code: 'VDF', latitude: '', longitude: '', name: "Val de Fontenay RER E"},
{code: 'VDO', latitude: '', longitude: '', name: "Le Val d'Or"},
{code: 'VDV', latitude: '', longitude: '', name: "Sèvres Ville d'Avray"},
{code: 'VEH', latitude: '', longitude: '', name: 'Villiers Neauphle Pontchartrain'},
{code: 'VEP', latitude: '', longitude: '', name: 'Villepreux les Clayes'},
{code: 'VET', latitude: '', longitude: '', name: 'Vernouillet Verneuil'},
{code: 'VFD', latitude: '', longitude: '', name: 'Viroflay Rive Droite'},
{code: 'VFG', latitude: '', longitude: '', name: 'Viroflay Rive Gauche'},
{code: 'VFR', latitude: '', longitude: '', name: 'Val de Fontenay RER A'},
{code: 'VGL', latitude: '', longitude: '', name: 'Vert Galant'},
{code: 'VGS', latitude: '', longitude: '', name: 'Vigneux sur Seine'},
{code: 'VIB', latitude: '', longitude: '', name: 'Villiers le Bel Gonesse Arnouville'},
{code: 'VII', latitude: '', longitude: '', name: 'Villeparisis Mitry Le Neuf'},
{code: 'VMD', latitude: '', longitude: '', name: 'Valmondois'},
{code: 'VMK', latitude: '', longitude: '', name: 'Vanves Malakoff'},
{code: 'VMS', latitude: '', longitude: '', name: 'Viarmes'},
{code: 'VNC', latitude: '', longitude: '', name: 'Vincennes'},
{code: 'VNL', latitude: '', longitude: '', name: "Verneuil l'Étang"},
{code: 'VOM', latitude: '', longitude: '', name: 'Vosves'},
{code: 'VP' , latitude: '', longitude: '', name: 'Villeneuve Prairie'},
{code: 'VPN', latitude: '', longitude: '', name: 'Villepinte'},
{code: 'VRD', latitude: '', longitude: '', name: 'Versailles Rive Droite'},
{code: 'VRG', latitude: '', longitude: '', name: 'Versailles Rive Gauche Château'},
{code: 'VRI', latitude: '', longitude: '', name: 'Villeneuve le Roi'},
{code: 'VSG', latitude: '', longitude: '', name: 'Villeneuve Saint-Georges'},
{code: 'VSM', latitude: '', longitude: '', name: 'Villiers sur Marne Plessis Trévise'},
{code: 'VSS', latitude: '', longitude: '', name: 'Vernou sur Seine'},
{code: 'VSW', latitude: '', longitude: '', name: 'Villennes sur Seine'},
{code: 'VTV', latitude: '', longitude: '', name: 'Villeneuve Triage'},
{code: 'VUN', latitude: '', longitude: '', name: 'Vulaines sur Seine Samoreau'},
{code: 'VW' , latitude: '', longitude: '', name: 'Villaines'},
{code: 'VWC', latitude: '', longitude: '', name: 'Viry Châtillon'},
{code: 'VWT', latitude: '', longitude: '', name: 'La Villetertre'},
{code: 'VXS', latitude: '', longitude: '', name: 'Vaux sur Seine'},
{code: 'VY' , latitude: '', longitude: '', name: 'Vitry sur Seine'},
{code: 'VYL', latitude: '', longitude: '', name: 'La Verrière'},
{code: 'WEE', latitude: '', longitude: '', name: 'Le Mée'},
{code: 'XBY', latitude: '', longitude: '', name: 'La Croix de Berny'},
{code: 'XCS', latitude: '', longitude: '', name: 'Saint-Colombe - Septveilles'},
{code: 'XFA', latitude: '', longitude: '', name: 'Saint-Fargeau'},
{code: 'XMC', latitude: '', longitude: '', name: 'Saint-Maur-Créteil'},
{code: 'XND', latitude: '', longitude: '', name: 'Saint-Michel Notre Dame RER B'},
{code: 'XOA', latitude: '', longitude: '', name: "Saint-Ouen l'Aumône Quartier de l'Église"},
{code: 'XPY', latitude: '', longitude: '', name: 'Santeuil - Le Perchay'},
{code: 'YES', latitude: '', longitude: '', name: 'Yerres'},
{code: 'ZTN', latitude: '', longitude: '', name: 'Savigny le Temple Nandy'},
{code: 'ZUB', latitude: '', longitude: '', name: 'Sucy Bonneuil'}
]);